const express=require('express')
const server=express()
const dummy=require('./controllers/simpleRoute')
const signup=require('./controllers/SignUp')
const signin=require('./controllers/Signin')
const search=require('./controllers/SearchUser')
const update=require('./controllers/UpdateUser')
const deleteUser=require('./controllers/DeleteUser')
const bp=require('body-parser')
server.use(bp.json())
server.use('/',dummy)
server.use('/',signup)
server.use('/',signin)
server.use('/',search)
server.use('/',update)
server.use('/',deleteUser)

server.listen(3001,()=>console.log('server started'))


